#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.10.19/phplist-2.10.19.tgz"
URL="http://sourceforge.net/projects/phplist/files/phplist/$VERSION"

dl $URL /usr/local/src

