#!/bin/sh -ex

DB_NAME=phplist
DB_USER=phplist
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey
ADMIN_MAIL=admin@example.com

SRC=/usr/local/src
WEBROOT=/var/www/phplist

# unpack
tar -zxf $SRC/phplist-*.tgz -C $SRC
mv $SRC/phplist-*/public_html/lists $WEBROOT
mkdir $WEBROOT/docs
mv $SRC/phplist-*/README* $WEBROOT/docs/
chown -R root:root $WEBROOT
rm -rf $SRC/phplist-*

# create phplist cli
PHPLIST_CLI=/usr/local/bin/phplist
cat >$PHPLIST_CLI<<EOF
#!/bin/bash -e
# Run phplist from the command line.
# Access is restricted to users listed in the config file, default: admin
# For reference see: $WEBROOT/docs/README.commandline

set \${USER:=admin}
export USER
export CONFIG=$WEBROOT/config/config.php
php5 $WEBROOT/admin/index.php \$*
EOF
chmod +x $PHPLIST_CLI

# create plugins placeholder
PHPLIST_PLUGINS=/var/www/phplist-plugins
mkdir -p $PHPLIST_PLUGINS
cat >$PHPLIST_PLUGINS/README.txt<<EOF
Create your own pages to slot into PHPlist, or do certain things are are more
specific to your situation.

For reference, see: $WEBROOT/admin/plugins
EOF

# configure apache
a2dissite default
a2ensite phplist
a2enmod rewrite

# start services
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop services
/etc/init.d/mysql stop

